---
- name: Create Azure PostgreSQL Database
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../../inventory/vars.yml
  tasks:
    - name: Create a PostgreSQL Database
      azure.azcollection.azure_rm_postgresqlflexibledatabase:
        resource_group: "{{ resource_group }}"
        server_name: "{{ postgres_server_name }}"
        name: "{{ postgres_database_name }}"
        charset: UTF8
        collation: en_US.utf8
        state: present
      register: postgres_database_result

    - name: Display PostgreSQL database details
      debug:
        var: postgres_database_result
