---
- name: Force Delete Resource Group
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../../inventory/vars.yml
  tasks:
    - name: Delete Resource Group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        state: absent
        force_delete_nonempty: yes
      register: rg_deletion

    - name: Display deletion status
      debug:
        msg: |
          Resource Group Deletion Initiated!
          Resource Group Name: {{ resource_group }}
          Verify deletion with:
          az group show --name {{ resource_group }}