- name: List Azure VMs in a Resource Group
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Get VMs in the resource group
      azure.azcollection.azure_rm_virtualmachine_info:
        resource_group: <-YOUR_RESOURCE_GROUP_NAME->
      register: vm_info

    - name: Show VM names
      debug:
        msg: "{{ item.name }}"
      loop: "{{ vm_info.vms }}"
